#!/bin/bash
# /etc/init.d/eborpclient

case "$1" in 
    start)
        echo "Starting eborpclient"
        /home/pi/setup.sh
        cd /home/pi/
        ./mon.sh | java -jar EborpClient-0.0.1-SNAPSHOT.jar > /dev/null &
        ;;
    stop)
        echo "Stopping eborpclient"
        killall java
        ;;
    *)
        echo "Usage: /etc/init.d/tsharkparser start|stop"
        exit 1
        ;;
esac

exit 0